# Generated by Django 4.0.6 on 2022-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_managers_delete_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turfmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_address', models.CharField(max_length=100)),
                ('manager_email', models.CharField(max_length=50)),
                ('manager_password', models.CharField(max_length=20)),
                ('manager_image', models.ImageField(upload_to='manager/')),
                ('manager_phone', models.BigIntegerField()),
                ('manager_status', models.CharField(default='pending', max_length=40)),
            ],
        ),
    ]
